if(MSVC)
    add_compile_options(/W4 /permissive-)
    if(VMS_WARNINGS_AS_ERRORS)
        add_compile_options(/WX)
    endif()
else()
    add_compile_options(-Wall -Wextra -Wpedantic)
    if(VMS_WARNINGS_AS_ERRORS)
        add_compile_options(-Werror)
    endif()
endif()

if(WIN32)
    add_compile_definitions(VMS_PLATFORM_WINDOWS)
else()
    add_compile_definitions(VMS_PLATFORM_LINUX)
endif()
